inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/attention.yaml
  - ../module_configs/prop_layer.yaml
  - ../module_configs/edge_aggregator.yaml
  - ../module_configs/ntn_edge.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding
    edge_embedding_dim: 20

  encoder_config:
    edge_hidden_sizes: [20]

  propagation_steps: 8
  alignment_feature_dim: 16
  # scoring params
  scoring: ntn
  # interaction params
  interaction_alignment: attention
  interaction_alignment_preprocessor_type: lrl
  interaction_when: post

name: gmn_edge_baseline_scoring=ntn___tp=attention_pp=lrl_when=post___K=8