inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/attention.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding
    edge_embedding_dim: 20

  encoder_config:
    edge_hidden_sizes: [20]

  propagation_steps: 3
  alignment_feature_dim: 16
  unify_scoring_and_interaction_preprocessor: True
  # scoring params
  scoring: set_aligned
  scoring_alignment: attention
  scoring_alignment_preprocessor_type: lrl
  # interaction params
  interaction_alignment: attention
  interaction_alignment_preprocessor_type: lrl
  interaction_when: post

name: gmn_edge_baseline_scoring=attention_pp=lrl___tp=attention_pp=lrl_when=post___unify=true___K=3