inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/attention.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_layer_config:
    prop_type: matching

  propagation_steps: 5
  alignment_feature_dim: 16
  unify_scoring_and_interaction_preprocessor: True
  # scoring params
  scoring: set_aligned
  scoring_alignment: masked_attention
  scoring_alignment_preprocessor_type: lrl
  # interaction params
  interaction_alignment: masked_attention
  interaction_alignment_preprocessor_type: lrl
  interaction_when: post

name: gmn_baseline_scoring=masked_attention_pp=lrl___tp=masked_attention_pp=lrl_when=post___unify=true