inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/attention.yaml
  - ../module_configs/prop_layer.yaml
  - ../module_configs/egsc_scoring.yaml

model_config:
  propagation_layer_config:
    prop_type: matching

  propagation_steps: 5
  alignment_feature_dim: 16
  # scoring params
  scoring: egsc_style
  # interaction params
  interaction_alignment: masked_attention
  interaction_alignment_preprocessor_type: lrl
  interaction_when: post

name: gmn_baseline_scoring=egsc___tp=masked_attention_pp=lrl_when=post