wandb_version: 1

time_updates:
  desc: null
  value: 1
time_update_index:
  desc: null
  value: k_t
'prop_param_sharing ':
  desc: null
  value: null
dataset:
  desc: null
  value: aids
task:
  desc: null
  value: temporal_isonet_kt_1_iters_shared_params
seed:
  desc: null
  value: 0
noise_factor:
  desc: null
  value: 0.0
feat_type:
  desc: null
  value: One
margin:
  desc: null
  value: 0.5
filters_1:
  desc: null
  value: 10
filters_2:
  desc: null
  value: 10
filters_3:
  desc: null
  value: 10
transform_dim:
  desc: null
  value: 16
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697727978.86771
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 76
      - 77
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
