inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/sinkhorn.yaml
  - ../module_configs/prop_layer.yaml
  - ../module_configs/aggregator.yaml

model_config:
  propagation_layer_config:
    prop_type: matching

  propagation_steps: 5
  alignment_feature_dim: 16
  # scoring params
  scoring: aggregated
  # interaction params
  interaction_alignment: sinkhorn
  interaction_alignment_preprocessor_type: identity
  interaction_when: post

name: gmn_baseline_scoring=agg___tp=sinkhorn_pp=identity_when=post