inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/attention.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_steps: 5
  attention_feature_dim: 16
  attention_mode: c_to_q
  masked_attention: False

name: nanl_attention_c_to_q
