inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/sinkhorn.yaml
  - ../module_configs/prop_layer.yaml
  - ../module_configs/aggregator.yaml
  - ../module_configs/ntn_node.yaml

model_config:
  propagation_layer_config:
    prop_type: matching

  propagation_steps: 5
  alignment_feature_dim: 16
  # scoring params
  scoring: ntn
  # interaction params
  interaction_alignment: sinkhorn
  interaction_alignment_preprocessor_type: hinge
  interaction_when: post

name: gmn_baseline_scoring=ntn___tp=sinkhorn_pp=hinge_when=post