inherit:
  - module_configs/encoder.yaml
  - module_configs/sinkhorn.yaml
  - module_configs/prop_layer.yaml

model_config:
  propagation_steps: 5
  sinkhorn_feature_dim: 16
  time_update_steps: 3
  propagation_layer_config:
    edge_embedding_dim: 30

name: edge_early_interaction_3