model_config:
  conf:
    input_dim: 1
    gnn_encoder: "GIN"      
    gnn_filters: [16, 16, 16]
    dropout: 0.

    deepsets: True
    use_bn: False
    deepsets_inner_act: "relu"      
    deepsets_outer_act: "relu"
    fuse_type: "cat"       # 'add', 'stack', 'cat'
    pooling: 'add'     # 'add', 'mean'
    reduction: 2
    inner_mlp: True       # 'mlp'
    inner_mlp_layers: 1
    outer_mlp_layers: 1

    use_sim: True
    NTN_layers: 1
    tensor_neurons: 16
    output_comb: True  

    use_ssl: True
    use_deepsets: False
    use_ff: False
    sep: False
    measure: 'JSD'

name: eric