inherit:
  - module_configs/encoder.yaml
  - module_configs/sinkhorn.yaml
  - module_configs/prop_layer.yaml

model_config:
  propagation_steps: 5
  time_update_steps: 3
  sinkhorn_feature_dim: 16
  propagation_layer_config:
    edge_embedding_dim: 30
  consistency_config:
    apply_transformation: False
    consistency_weight: 0.7

name: node_edge_early_interaction_consistency
