inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/sinkhorn.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_steps: 5

  propagation_layer_config:
    prop_type: embedding
    edge_embedding_dim: 20

  encoder_config:
    edge_hidden_sizes: [20]

  sinkhorn_feature_dim: 16

name: isonet
