inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/prop_layer.yaml
  - ../module_configs/edge_aggregator.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding
    edge_embedding_dim: 20

  encoder_config:
    edge_hidden_sizes: [20]

  propagation_steps: 5
  # scoring params
  scoring: neural
  # interaction params
  interaction_when: never

name: gmn_edge_baseline_scoring=neural___tp=none