inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/sinkhorn.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding
    edge_embedding_dim: 20

  encoder_config:
    edge_hidden_sizes: [20]

  propagation_steps: 5
  alignment_feature_dim: 16
  unify_scoring_and_interaction_preprocessor: True
  # scoring params
  scoring: set_aligned
  scoring_alignment: sinkhorn
  scoring_alignment_preprocessor_type: hinge
  # interaction params
  interaction_alignment: sinkhorn
  interaction_alignment_preprocessor_type: hinge
  interaction_when: post

name: gmn_edge_baseline_scoring=sinkhorn_pp=hinge___tp=sinkhorn_pp=hinge_when=post___unify=true