inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/sinkhorn.yaml
  - ../module_configs/prop_layer.yaml
  - ../module_configs/edge_aggregator.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding
    edge_embedding_dim: 20

  encoder_config:
    edge_hidden_sizes: [20]

  propagation_steps: 5
  alignment_feature_dim: 16
  # scoring params
  scoring: neural
  # interaction params
  interaction_alignment: sinkhorn
  interaction_alignment_preprocessor_type: hinge
  interaction_when: post

name: gmn_edge_baseline_scoring=neural___tp=sinkhorn_pp=hinge_when=post