inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/attention.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_steps: 5
  attention_feature_dim: 16
  attention_mode: q_to_c
  masked_attention: True

name: nanl_masked_attention_q_to_c
