inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/sinkhorn.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding

  propagation_steps: 5
  # scoring params
  scoring: set_aligned
  scoring_alignment: sinkhorn
  scoring_alignment_preprocessor_type: identity
  # interaction params
  interaction_when: never

name: gmn_baseline_scoring=sinkhorn_pp=identity___tp=none