inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/prop_layer.yaml
  - ../module_configs/aggregator.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding

  propagation_steps: 5
  # scoring params
  scoring: neural
  # interaction params
  interaction_when: never

name: gmn_baseline_scoring=neural___tp=none