inherit:
  - ../module_configs/encoder.yaml
  - ../module_configs/attention.yaml
  - ../module_configs/prop_layer.yaml

model_config:
  propagation_layer_config:
    prop_type: embedding

  propagation_steps: 5
  alignment_feature_dim: 16
  # scoring params
  scoring: set_aligned
  scoring_alignment: attention
  scoring_alignment_preprocessor_type: identity
  # interaction params
  interaction_when: never

name: gmn_baseline_scoring=attention_pp=identity___tp=none